// This file was auto-generated by Fern from our API Definition.

/**
 * NodeJS runtime information model
 */
export interface NodeJsRuntimeInfo {
    /** Node.js version */
    node_version: string;
    /** npm version */
    npm_version: string;
    /** List of supported languages */
    supported_languages: string[];
    /** Service description */
    description: string;
    /** Runtime directory path */
    runtime_directory?: string;
    /** Error message if runtime info retrieval failed */
    error?: string;
}
