// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Process termination result model
 */
export interface ShellKillResult {
    /** Process status */
    status: Sandbox.BashCommandStatus;
    /** Process return code */
    returncode: number;
}
