// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "code"
 *     }
 */
export interface JupyterExecuteRequest {
    /** Python code to execute */
    code: string;
    /** Execution timeout in seconds */
    timeout?: number;
    /** Kernel name to use (e.g., 'python3', 'python3.11', 'python3.12'). Defaults to 'python3' */
    kernel_name?: string;
    /** Session ID to maintain kernel state across requests */
    session_id?: string;
}
