// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface JupyterCreateSessionRequest {
    /** Unique identifier for the session, auto-generated if not provided */
    session_id?: string;
    /** Kernel name to use (e.g., 'python3', 'python3.11', 'python3.12'). Defaults to 'python3' */
    kernel_name?: string;
}
