// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         language: "python",
 *         code: "code"
 *     }
 */
export interface CodeExecuteRequest {
    /** Target runtime language */
    language: Sandbox.Language;
    /** Source code to execute */
    code: string;
    /** Execution timeout in seconds */
    timeout?: number;
}
