// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ShellCreateSessionRequest {
    /** Unique identifier for the shell session, auto-generated if not provided */
    id?: string;
    /** Working directory for the new session (must use absolute path) */
    exec_dir?: string;
}
