// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         command: "command"
 *     }
 */
export interface ShellExecRequest {
    /** Unique identifier of the target shell session, if not provided, one will be automatically created */
    id?: string;
    /** Working directory for command execution (must use absolute path) */
    exec_dir?: string;
    /** Shell command to execute */
    command: string;
    /** Whether to execute command asynchronously (default: False for async, False for synchronous execution) */
    async_mode?: boolean;
    /** Maximum time (seconds) to wait for command completion before returning running status */
    timeout?: number;
}
