// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "code"
 *     }
 */
export interface NodeJsExecuteRequest {
    /** JavaScript code to execute */
    code: string;
    /** Execution timeout in seconds */
    timeout?: number;
    /** Standard input for the process */
    stdin?: string;
    /** Additional files to create in execution directory */
    files?: Record<string, string | undefined>;
}
